use drset2014;
INSERT INTO `drset2014`.`usert` (`USER_NAME`, `USER_LNAME`, `USER_SEX`, `USER_UNIQEMAIL`, `USER_UNIQLOGIN`, `USER_PASSWORD`, `USER_DATEINSCRIP`, `USER_SATUSACTIVE`, `USERT_TERMOUSO`) VALUES ('Igor', 'Lemos Alves', '1', 'igor', 'igoralves1', '123456', '2014-09-08', '0', '1');
    
INSERT INTO `drset2014`.`professional` (`PROFESSIONAL_FKUSER`, `PROFESSIONAL_FKPROFESSION`) VALUES ('1', '11');
    
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('1', '132');
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('1', '136');
    
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('11', '1', '123456789');
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('24', '1', '000000000');
    
INSERT INTO language_user (LANGUAGE_USER_FKLANG, LANGUAGE_USER_FKUSER) VALUES ("1", "1");

INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('1', '1');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('1', '2');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('1', '3');
    
/*Inserir endereço*/
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Moradia Pessoal Igor', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso I Igor', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso II Igor', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
    
/*Fazer links de endereços Pessoal e Profissional*/
INSERT INTO `drset2014`.`user_address` (`USER_ADDRESS_FKUSER`, `USER_ADDRESS_FKADDRESS`) VALUES ('1', '1');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('2', '1');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('3', '1');
    
/*Fazer links de endereços Profissional e Porcentagem*/
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('1', '2014-01-01', '37');
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('2', '2014-01-01', '32');
    


SELECT * FROM drset2014.usert;
SELECT * FROM drset2014.professional;

SELECT * FROM drset2014.professinal_especialization WHERE PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL=1;
SELECT * FROM drset2014.professional_permit WHERE PROFESSIONAL_PERMIT_FKPROFESSIONAL=1;
SELECT * FROM drset2014.educational_level_professional WHERE EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF=1;

SELECT * FROM drset2014.address;

SELECT * FROM drset2014.professional_addrss WHERE PROFESSIONAL_ADDRSS_FKPROFESSIONAL=1;

SELECT 
UST.USER_NAME, 
ADDR.ADDRESS_NOME, 
ADDR.ADDRESS_ATIVO, 

PA.PROFESSIONAL_ADDRSS_PK,
 
PP.PROFISSIONAL_PORCENTAGEM_PORCENT,
PP.PROFISSIONAL_PORCENTAGEM_Pk,
PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA,
PP.PROFISSIONAL_PORCENTAGEM_DATA  

FROM 
profissional_porcentagem AS PP
	INNER JOIN professional_addrss AS PA
		ON(PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA=PA.PROFESSIONAL_ADDRSS_PK)

	INNER JOIN address ADDR
		ON(PA.PROFESSIONAL_ADDRSS_FKADDRSS=ADDR.ADDRESS_Pk)

	INNER JOIN professional PF
		ON(PA.PROFESSIONAL_ADDRSS_FKPROFESSIONAL=PF.PROFESSIONAL_Pk)

	INNER JOIN usert AS UST
		ON(PF.PROFESSIONAL_FKUSER=UST.USER_Pk)


WHERE UST.USER_Pk=1
AND ADDR.ADDRESS_ATIVO=1;
/*============================================================================================================*/

INSERT INTO `drset2014`.`usert` (`USER_NAME`, `USER_LNAME`, `USER_SEX`, `USER_UNIQEMAIL`, `USER_UNIQLOGIN`, `USER_PASSWORD`, `USER_DATEINSCRIP`, `USER_SATUSACTIVE`, `USERT_TERMOUSO`) VALUES ('Alex', 'Bruno Alves', '1', 'alex', 'alex1', '123456', '2014-09-08', '0', '1');
INSERT INTO `drset2014`.`professional` (`PROFESSIONAL_FKUSER`, `PROFESSIONAL_FKPROFESSION`) VALUES ('2', '11');
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('2', '132');
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('2', '136');
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('11', '2', '222222222');
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('24', '2', '333333333');
INSERT INTO language_user (LANGUAGE_USER_FKLANG, LANGUAGE_USER_FKUSER) VALUES ("1", "2");

INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('2', '1');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('2', '2');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('2', '3');
/*Inserir endereço*/
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Moradia Pessoal Alex', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso I Alex', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso II Alex', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso III Alex', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
/*Fazer links de endereços Pessoal e Profissional*/
INSERT INTO `drset2014`.`user_address` (`USER_ADDRESS_FKUSER`, `USER_ADDRESS_FKADDRESS`) VALUES ('2', '4');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('5', '2');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('6', '2');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('7', '2');
/*Fazer links de endereços Profissional e Porcentagem*/
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('3', '2014-01-01', '36');
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('4', '2014-01-01', '7');
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('5', '2014-01-01', '10');



SELECT * FROM drset2014.usert;
SELECT * FROM drset2014.professional;

SELECT * FROM drset2014.professinal_especialization WHERE PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL=2;
SELECT * FROM drset2014.professional_permit WHERE PROFESSIONAL_PERMIT_FKPROFESSIONAL=2;
SELECT * FROM drset2014.educational_level_professional WHERE EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF=2;

SELECT * FROM drset2014.address;

SELECT * FROM drset2014.professional_addrss WHERE PROFESSIONAL_ADDRSS_FKPROFESSIONAL=2;

SELECT 
UST.USER_NAME, 
ADDR.ADDRESS_NOME, 
ADDR.ADDRESS_ATIVO, 

PA.PROFESSIONAL_ADDRSS_PK,
 
PP.PROFISSIONAL_PORCENTAGEM_PORCENT,
PP.PROFISSIONAL_PORCENTAGEM_Pk,
PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA,
PP.PROFISSIONAL_PORCENTAGEM_DATA  

FROM 
profissional_porcentagem AS PP
	INNER JOIN professional_addrss AS PA
		ON(PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA=PA.PROFESSIONAL_ADDRSS_PK)

	INNER JOIN address ADDR
		ON(PA.PROFESSIONAL_ADDRSS_FKADDRSS=ADDR.ADDRESS_Pk)

	INNER JOIN professional PF
		ON(PA.PROFESSIONAL_ADDRSS_FKPROFESSIONAL=PF.PROFESSIONAL_Pk)

	INNER JOIN usert AS UST
		ON(PF.PROFESSIONAL_FKUSER=UST.USER_Pk)


WHERE UST.USER_Pk=2
AND ADDR.ADDRESS_ATIVO=1;
/*============================================================================================================*/

INSERT INTO `drset2014`.`usert` (`USER_NAME`, `USER_LNAME`, `USER_SEX`, `USER_UNIQEMAIL`, `USER_UNIQLOGIN`, `USER_PASSWORD`, `USER_DATEINSCRIP`, `USER_SATUSACTIVE`, `USERT_TERMOUSO`) VALUES ('Soph', 'Bruno Alves', '1', 'Soph', 'soph1', '123456', '2014-09-08', '0', '1');
INSERT INTO `drset2014`.`professional` (`PROFESSIONAL_FKUSER`, `PROFESSIONAL_FKPROFESSION`) VALUES ('3', '11');
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('3', '132');
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('3', '136');
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('11', '3', '222222222');
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('24', '3', '333333333');
INSERT INTO language_user (LANGUAGE_USER_FKLANG, LANGUAGE_USER_FKUSER) VALUES ("1", "3");

INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('3', '1');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('3', '2');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('3', '3');
/*Inserir endereço*/
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Moradia Pessoal Soph', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso I Soph', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso II Soph', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso III Soph', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso IV Soph', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso V Soph', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
/*Fazer links de endereços Pessoal e Profissional*/
INSERT INTO `drset2014`.`user_address` (`USER_ADDRESS_FKUSER`, `USER_ADDRESS_FKADDRESS`) VALUES ('3', '8');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('9', '3');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('10', '3');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('11', '3');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('12', '3');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('13', '3');
/*Fazer links de endereços Profissional e Porcentagem*/
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('6', '2014-01-01', '38');
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('7', '2014-01-01', '71');
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('8', '2014-01-01', '13');
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('9', '2014-01-01', '26');
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('10', '2014-01-01', '17');






SELECT * FROM drset2014.usert;
SELECT * FROM drset2014.professional;

SELECT * FROM drset2014.professinal_especialization WHERE PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL=3;
SELECT * FROM drset2014.professional_permit WHERE PROFESSIONAL_PERMIT_FKPROFESSIONAL=3;
SELECT * FROM drset2014.educational_level_professional WHERE EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF=3;

SELECT * FROM drset2014.address;

SELECT * FROM drset2014.professional_addrss WHERE PROFESSIONAL_ADDRSS_FKPROFESSIONAL=3;

SELECT 
UST.USER_NAME, 
ADDR.ADDRESS_NOME, 
ADDR.ADDRESS_ATIVO, 

PA.PROFESSIONAL_ADDRSS_PK,
 
PP.PROFISSIONAL_PORCENTAGEM_PORCENT,
PP.PROFISSIONAL_PORCENTAGEM_Pk,
PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA,
PP.PROFISSIONAL_PORCENTAGEM_DATA  

FROM 
profissional_porcentagem AS PP
	INNER JOIN professional_addrss AS PA
		ON(PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA=PA.PROFESSIONAL_ADDRSS_PK)

	INNER JOIN address ADDR
		ON(PA.PROFESSIONAL_ADDRSS_FKADDRSS=ADDR.ADDRESS_Pk)

	INNER JOIN professional PF
		ON(PA.PROFESSIONAL_ADDRSS_FKPROFESSIONAL=PF.PROFESSIONAL_Pk)

	INNER JOIN usert AS UST
		ON(PF.PROFESSIONAL_FKUSER=UST.USER_Pk)


WHERE UST.USER_Pk=3
AND ADDR.ADDRESS_ATIVO=1;
/*============================================================================================================*/

INSERT INTO `drset2014`.`usert` (`USER_NAME`, `USER_LNAME`, `USER_SEX`, `USER_UNIQEMAIL`, `USER_UNIQLOGIN`, `USER_PASSWORD`, `USER_DATEINSCRIP`, `USER_SATUSACTIVE`, `USERT_TERMOUSO`) VALUES ('Raq', 'Bruno Alves', '1', 'Raq', 'Raq1', '123456', '2014-09-08', '0', '1');
INSERT INTO `drset2014`.`professional` (`PROFESSIONAL_FKUSER`, `PROFESSIONAL_FKPROFESSION`) VALUES ('4', '11');/*Ate aqui*/
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('4', '132');
INSERT INTO `drset2014`.`professinal_especialization` (`PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL`, `PROFESSINAL_ESPECIALIZATION_FKESPECIALIZ`) VALUES ('4', '136');
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('11', '4', '444444');
INSERT INTO `drset2014`.`professional_permit` (`PROFESSIONAL_PERMIT_FKASSOCIATION`, `PROFESSIONAL_PERMIT_FKPROFESSIONAL`, `PROFESSIONAL_PERMIT_FKNUMBER`) VALUES ('24', '4', '444455');
INSERT INTO language_user (LANGUAGE_USER_FKLANG, LANGUAGE_USER_FKUSER) VALUES ("1", "4");

INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('4', '1');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('4', '2');
INSERT INTO `drset2014`.`educational_level_professional` (`EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF`, `EDUCATIONAL_LEVEL_PROFESSIONAL_FKLEVEL`) VALUES ('4', '3');
/*Inserir endereço*/
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Moradia Pessoal Raq', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso I Raq', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
INSERT INTO `drset2014`.`address` (`ADDRESS_FKCITY`, `ADDRESS_NOME`, `ADDRESS_NBASTREET`, `ADDRESS_ZIP`, `ADDRESS_CELL`, `ADDRESS_TELL`, `ADDRESS_FAX`, `ADDRESS_EMAIL`, `ADDRESS_URL`, `ADDRESS_YOUTUBE`, `ADDRESS_SKYPE`, `ADDRESS_TWITTER`, `ADDRESS_FACEBOOK`, `ADDRESS_LATITUDE`, `ADDRESS_LOMGITUDE`, `ADDRESS_NOTAPRIVADA`, `ADDRESS_NOTAPUBLICA`) VALUES ('1', 'Clinica Sorriso II Raq', '10315 Romuald Trudeau', 'H4N2X5', '514 6775099', '514 6775099', '514 6775099', 'igoralves1@gmail.com', 'www.drreference.com/drIgor', 'www.youtube.com/gaso', 'igor.alves', 'igordrt', 'Dr igor Lemos', '10,40,89', '19.89.90', 'Clinica com muitos pacirntes pobres', 'Atendemos urgencias');
/*Fazer links de endereços Pessoal e Profissional*/
INSERT INTO `drset2014`.`user_address` (`USER_ADDRESS_FKUSER`, `USER_ADDRESS_FKADDRESS`) VALUES ('4', '14');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('15', '4');
INSERT INTO `drset2014`.`professional_addrss` (`PROFESSIONAL_ADDRSS_FKADDRSS`, `PROFESSIONAL_ADDRSS_FKPROFESSIONAL`) VALUES ('16', '4');
/*Fazer links de endereços Profissional e Porcentagem*/
INSERT INTO `drset2014`.`profissional_porcentagem` (`PROFISSIONAL_PORCENTAGEM_FK_CLINICA`, `PROFISSIONAL_PORCENTAGEM_DATA`, `PROFISSIONAL_PORCENTAGEM_PORCENT`) VALUES ('11', '2014-01-01', '38');






SELECT * FROM drset2014.usert;
SELECT * FROM drset2014.professional;

SELECT * FROM drset2014.professinal_especialization WHERE PROFESSINAL_ESPECIALIZATION_FKPROFESSIONAL=4;
SELECT * FROM drset2014.professional_permit WHERE PROFESSIONAL_PERMIT_FKPROFESSIONAL=4;
SELECT * FROM drset2014.educational_level_professional WHERE EDUCATIONAL_LEVEL_PROFESSIONAL_FKPROF=4;

SELECT * FROM drset2014.address;

SELECT * FROM drset2014.professional_addrss WHERE PROFESSIONAL_ADDRSS_FKPROFESSIONAL=4;

SELECT 
UST.USER_NAME, 
ADDR.ADDRESS_NOME, 
ADDR.ADDRESS_ATIVO, 

PA.PROFESSIONAL_ADDRSS_PK,
 
PP.PROFISSIONAL_PORCENTAGEM_PORCENT,
PP.PROFISSIONAL_PORCENTAGEM_Pk,
PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA,
PP.PROFISSIONAL_PORCENTAGEM_DATA  

FROM 
profissional_porcentagem AS PP
	INNER JOIN professional_addrss AS PA
		ON(PP.PROFISSIONAL_PORCENTAGEM_FK_CLINICA=PA.PROFESSIONAL_ADDRSS_PK)

	INNER JOIN address ADDR
		ON(PA.PROFESSIONAL_ADDRSS_FKADDRSS=ADDR.ADDRESS_Pk)

	INNER JOIN professional PF
		ON(PA.PROFESSIONAL_ADDRSS_FKPROFESSIONAL=PF.PROFESSIONAL_Pk)

	INNER JOIN usert AS UST
		ON(PF.PROFESSIONAL_FKUSER=UST.USER_Pk)


WHERE UST.USER_Pk=4
AND ADDR.ADDRESS_ATIVO=1;





INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('FHJGFHDFGDG', 'DFWRTGDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('XCVBGFDG', 'DFGWRETDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('GFDG', 'DFGDTWRTFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('LHJKLGFDFGHDDG', 'DWERTFGDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('QEWGFDG', 'DFGDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('SADFGTFHDFDG', 'DFWERTERGDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('CVBGFDG', 'DFGDWERTWERFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('ILYGWERTHDFGFDG', 'DFWERTGDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('LJGHDGFFDG', 'DFGDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('BNMGFERTWERDG', 'DFGTDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('NMGHFHJWERFDG', 'DFWERTGDFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('VNMGFTWERTDG', 'DFGDWERTFG');
INSERT INTO `paciente` (`PACIENTE_NOME`, `PACIENTE_EMAIL`) VALUES ('WERGTWERTWFDG', 'DFGWERTDFG');


